Repository Year-3-Assignments/school-frontend-v1, pull requests merged in 2021-08, with the labels that each got.

#1 Implement React Redux configurations
  .prettierrc
  package-lock.json
  package.json
  src/App.js
  src/Routes.js
  src/actions/index.js
  src/components/sample_component.js
  src/index.js
  src/pages/sample_page.js
  src/reducers/index.js
  src/store.js
Labels: configuration, good first issue

#2 Create Examination
  .env
  .github/workflows/firebase.yml
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/App.test.js
  src/Routes.js
  src/actions/examination_actions.js
  src/actions/index.js
  src/assets/loader.gif
  src/components/loader.js
  src/components/sample_component.js
  src/index.css
  src/pages/examination/teacher/add/create_new_exam.js
  src/pages/examination/teacher/add/create_new_question.js
  src/pages/examination/teacher/add/custom_form.scss
  src/pages/examination/teacher/update/update_exam.js
  src/pages/examination/teacher/view/examination.js
  src/pages/examination/teacher/view/examination_page.js
  src/pages/examination/teacher/view/questions.js
  src/reducers/examination_reducer.js
  src/reducers/index.js
  yarn.lock
Labels: enhancement, UI

#3 Fix error in examination page
  .env
  src/pages/examination/teacher/add/create_new_exam.js
Labels: enhancement, bug-fix

#5 Creating a pull request for member/raveena
  .env
  package-lock.json
  src/Routes.js
  src/actions/index.js
  src/actions/student_actions.js
  src/components/progress.js
  src/firebase.config.js
  src/pages/sample_page.js
  src/pages/student/add/student.css
  src/pages/student/add/student.js
  src/pages/student/view/student_view.css
  src/pages/student/view/student_view.js
  src/reducers/index.js
  src/reducers/student_reducer.js
  yarn.lock
Labels: bug, help wanted, UI

#10 Member/rusiru
  .dockerignore
  Dockerfile
  src/App.css
  src/App.js
  src/App.scss
  src/Routes.js
  src/actions/index.js
  src/actions/user_actions.js
  src/assets/background_2.jpg
  src/assets/login-image.gif
  src/assets/login_background.jpg
  src/assets/school-logo.png
  src/components/navigation_bar.js
  src/index.css
  src/pages/examination/teacher/view/examination.js
  src/pages/examination/teacher/view/examination.scss
  src/pages/examination/teacher/view/examination_page.js
  src/pages/examination/teacher/view/questions.js
  src/pages/login/login_page.js
  src/pages/login/login_page.scss
  src/pages/sample_page.js
  src/reducers/index.js
  src/reducers/user_reducer.js
Labels: enhancement, UI

#8 Member/raveena
  .env
  package-lock.json
  package.json
  src/Routes.js
  src/actions/index.js
  src/actions/student_actions.js
  src/components/progress.js
  src/firebase.config.js
  src/pages/student/add/student.css
  src/pages/student/add/student.js
  src/pages/student/view/student_view.css
  src/pages/student/view/student_view.js
  src/reducers/index.js
  src/reducers/student_reducer.js
  src/store.js
  yarn.lock
Labels: enhancement, UI
